name: CI-Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # 允许创建 Tag 和 Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # ---------- 1. 拉代码 ----------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # 需要完整历史

      # ---------- 2. 环境 ----------
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      # ---------- 3. 构建 ----------
      - name: Build plugin
        run: mvn clean package -B

      # ---------- 4. 计算版本号 ----------
      - name: Calc next tag
        id: tag
        run: |
          # 取今天日期 20251003
          today=$(date +%Y%m%d)
          # 查找今天已发布的 tag：v20251003.1  v20251003.2 ...
          latestToday=$(git tag -l "v${today}.*" --sort=-version:refname | head -n1)
          if [[ -z "$latestToday" ]]; then
            seq=1
          else
            seq=$((${latestToday##*.} + 1))
          fi
          next="v${today}.${seq}"
          echo "tag=$next" >> $GITHUB_OUTPUT
          echo "Next tag will be: $next"

      # ---------- 5. 打 tag 并 push ----------
      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      # ---------- 6. 创建 Release 并上传 jar ----------
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "自动构建 ${{ steps.tag.outputs.tag }}"
          body: "推送触发自动发布，详见提交记录。"
          files: target/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
